name: 完美校园低电费提醒
on:
  schedule:
    - cron: "0 4,11 * * *"  # 世界协调时，相当于北京时间每天 12 点和 19 点各运行一次
    
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installation dependencies
        run: |
          sudo apt-get update -y  
          sudo apt-get install -y curl jq

      - name: Run main.sh
        env:
          QMSG_KEY: ${{ secrets.QMSG_KEY }}
          SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
          STUDENT_ID: ${{ secrets.STUDENT_ID }}
          ALERT_QQ: ${{ secrets.ALERT_QQ }}
          ALERT_THRESHOLD: ${{ vars.ALERT_THRESHOLD }}
        run: |
          chmod 755 ./main.sh
          ./main.sh
